app:
    resource: "@WCSShareKanBundle/Resources/config/routing.yml"
    type: rest
    prefix: /api

api_login_check:
  path: /api/login_check

wcs_share_kan_homepage:
    path:     /
    defaults: { _controller: WCSShareKanBundle:Default:index }
