
login:
    path:  /login
    defaults: { _controller: WCSShareKanBundle:Default:index }

api_playlist_add:
    path: /playlist/add
    defaults: { _controller: WCSShareKanBundle:Playlist:add }

api_playlist_delete:
    path: /playlist/delete
    defaults: { _controller: WCSShareKanBundle:Playlist:delete }

api_playlist_update:
    path: /playlist/update
    defaults: { _controller: WCSShareKanBundle:Playlist:update }

api_playlist_get:
    path: /playlist/get
    defaults: { _controller: WCSShareKanBundle:Playlist:get }

api_playlist_all:
    path: /playlist/get/all
    defaults: { _controller: WCSShareKanBundle:Playlist:getall }

api_get_user_actual:
    path: /user/get/actual
    defaults: { _controller: WCSShareKanBundle:Default:actualUser }

api_get_user_invite:
    path: /user/invite
    defaults: { _controller: WCSShareKanBundle:Default:invite }